### PR TITLE
Redux integration

### PR DESCRIPTION
**Pull request by nushydude**
The main change is Redux integration. Data is still not fetched from an API, but it should be easy to integrate it now.

Also moved the App and DetailPage to src/components. Everything we write should be put inside src. 

Made some logical name changes to the Components names and variables.

### CODE REVIEW

**Comment by agentmilindu** [comment]
Awesome job there! Can you resolve the conflicts and push? Then I can merge the branch! :)

**Comment by nushydude** [comment]
How do I do that? It says the "conflicts are too complex to resolve in the web editor" and as a result, the `Resolve conflicts` button is greyed out.

I cannot see where the conflicts are. I tried merging the changes to an up-to-date master, but I never got any conflicts.

Is there a way I can "see" the files with merge conflicts, that would be helpful.

**Comment by agentmilindu** [comment]
Oh, I have somehow missed your last message. I'll fix this.

**Comment by nushydude** [comment]
Thanks

**Comment by agentmilindu** [comment]
Hi @nushydude, finally got some time to resolve merge conflicts and merge this! BTW, awesome job.

**Pull request merged**
