### PR TITLE
Get thumbnails for categories and sites from Firebase Hosting

### LINKED ISSUE #32: Get thumbnails for categories and sites from Firebase Hosting
We need to fetch thumbnails for categories and sites from Firebase Hosting where we can dynamically add or change them.

### PR DESCRIPTION
**Pull request by TheLukaszNs**
What this PR can help with?
===
This PR fixes #32, modifies `Api` class and adds new package:
- [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob)

Note!
===
For now thumbnails are fetched from firebase, stored in local storage, but they are *not* deleted! This means that we should delete these files or override them (for example by specifying **path**). I'll think about it and fix it in one of next commits.

---
> I'm ready to see lists of bugs and I'm looking forward to fix it 🤣. For now: **Happy New Year!** 🎉

### CODE REVIEW

**Comment by TheLukaszNs** [comment]
Also, we should delete files stored locally (except for UNKNOWN), because we **don't need them** anymore!
> I didn't do it so that there would be no migration errors.

**Comment by agentmilindu** [comment]
@TheLukaszNs See #40

**Comment by TheLukaszNs** [comment]
@agentmilindu task has been taken or something? I can't take it 😞

**Comment by agentmilindu** [comment]
@TheLukaszNs Check now.

BTW, please join the Gitter chat https://gitter.im/CodeLanka/ez-net-app

**Pull request merged**
